const GET_STATE = "GET_STATE";
const SEND_MESSAGES = "SEND_MESSAGES";
const SEND_FOLLOW_ID = "SEND_FOLLOW_ID";
const SEND_USER_ID = "SEND_USER_ID";
const USER_ID_KEY = "USER_ID_KEY";
const NEXT_PERSON = "NEXT_PERSON";
const SET_MESSAGE = "SET_MESSAGE";
const GET_MESSAGE = "GET_MESSAGE";
const FOLLOW_IDS_KEY = "FOLLOW_IDS_KEY";
const GET_TEMP_COMMENT = "GET_TEMP_COMMENT";
const SET_TEMP_COMMENT = "SET_TEMP_COMMENT";
const ACTIVITY_TRACK = "ACTIVITY_TRACK";
const ACTIVITY_NAMES = {
    FOLLOWS: "follows",
    TWEETS: "tweets",
    MESSAGES: "messages"
};
const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
const CHECK_CAP = "CHECK_CAP";
